<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'commands' => '/includes/class-commands.php',
                'nicomv\\data_manager\\controllers\\admin_controller' => '/controllers/class-admin-controller.php',
                'nicomv\\data_manager\\controllers\\challenge_controller' => '/controllers/class-challenge-controller.php',
                'nicomv\\data_manager\\includes\\comparer' => '/includes/class-comparer.php',
                'nicomv\\data_manager\\includes\\data_result' => '/includes/class-data-result.php',
                'nicomv\\data_manager\\includes\\data_service' => '/includes/class-data-service.php',
                'nicomv\\data_manager\\includes\\sortable' => '/includes/class-sortable.php',
                'nicomv\\data_manager\\includes\\sorter' => '/includes/class-sorter.php',
                'nicomv\\data_manager\\includes\\utils\\data_result_filter' => '/includes/utils/class-data-result-filter.php',
                'nicomv\\data_manager\\includes\\utils\\data_result_helper' => '/includes/utils/class-data-result-helper.php',
                'nicomv\\data_manager\\includes\\utils\\template_utils' => '/includes/utils/class-template-utils.php',
                'nicomv\\data_manager\\main' => '/class-main.php',
                'nicomv\\data_manager\\shortcodes\\data_manager' => '/shortcodes/class-data-manager.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
